--
-- PostgreSQL database dump
--

\restrict IRESrfHz4ooK9o20nQoQDuTle3yrj7bXsyKauwhPDJH6iKCv3D2fWkh7akm57mH

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appointment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appointment (
    id bigint NOT NULL,
    appointment_date date,
    appointment_time time(0) without time zone,
    calendar_event_id character varying(255),
    doctor_notes text,
    post_visit_summary text,
    pre_visit_summary text,
    status character varying(255),
    symptoms text,
    doctor_id bigint,
    patient_id bigint,
    CONSTRAINT appointment_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appointment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctor (
    id bigint NOT NULL,
    slot_duration_minutes integer,
    specialization character varying(255),
    working_hours_end character varying(255),
    working_hours_start character varying(255),
    user_id bigint NOT NULL
);


--
-- Name: doctor_leave_days; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctor_leave_days (
    doctor_id bigint NOT NULL,
    leave_days date
);


--
-- Name: doctor_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.doctor_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: prescription; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prescription (
    id bigint NOT NULL,
    duration_days integer NOT NULL,
    frequency_per_day integer NOT NULL,
    instructions character varying(255),
    medication_name character varying(255),
    appointment_id bigint
);


--
-- Name: prescription_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.prescription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['PATIENT'::character varying, 'DOCTOR'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: appointment; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.appointment (id, appointment_date, appointment_time, calendar_event_id, doctor_notes, post_visit_summary, pre_visit_summary, status, symptoms, doctor_id, patient_id) FROM stdin;
1	2026-09-19	12:30:00	8nk2aets06pk8l1husdro7hqck	\N	\N	\N	CANCELLED		1	3
2	2026-09-19	13:00:00	6iq8r1rt0cj59d23nq1hkbvct4	\N	\N	\N	CONFIRMED		1	3
3	2026-09-19	12:00:00	v8u6cifrhb7513v8nl7n5lnkn8	\N	\N	\N	CONFIRMED		1	7
4	2026-09-20	16:00:00	3s59c93f6sona0gab3qa0qnk34	\N	\N	\N	CONFIRMED		1	8
5	2026-09-20	14:00:00	\N	\N	\N	Pre-visit summary unavailable.	CONFIRMED	Fever, headache, body ache, fatigue, and mild sore throat for the past 2 days	1	7
6	2026-09-25	14:00:00	\N	\N	\N	Pre-visit summary unavailable.	CONFIRMED	have had a headache since yesterday, mild fever, and feel tired	1	7
7	2026-09-21	14:00:00	c4510jh2vr57da6s7d29m67p7c	\N	\N	Pre-visit summary unavailable.	CONFIRMED	I have headache, mild fever and tiredness since yesterday.	1	9
8	2026-10-12	14:00:00	ie8cq04d6ndjet2u7n0re2jm1s	\N	\N	Pre-visit summary unavailable.	CONFIRMED	I have had a headache since yesterday, mild fever, and feel tired.	1	7
9	2026-10-20	12:30:00	tbo80gatht0u12j9coe9jd0fg4	\N	\N	Pre-visit summary unavailable.	CONFIRMED	I have headache and mild fever	2	7
10	2026-10-25	12:30:00	32q8arr8ufii42ld0jl672kmn0	\N	\N	Pre-visit summary unavailable.	CONFIRMED	I have headache and mild fever	2	7
11	2026-11-25	12:30:00	74f985g9l2i6r27vebqb62e300	\N	\N	**1. Urgency Level:** **Low‑to‑Medium**  \n- A mild fever and headache are often benign (e.g., viral upper‑respiratory infection, tension‑type headache).  \n- However, the level can rise to **Medium** if the headache is new, worsening, or accompanied by concerning features (neck stiffness, neurological changes, severe pain, recent trauma, immunosuppression, etc.). If any red‑flag symptoms are present, seek care promptly (Emergency/High).\n\n**2. Chief Complaint (CC):**  \n- “I have a headache and a mild fever.”\n\n**3. Three key questions the physician should ask**\n\n| # | Question | Why it matters |\n|---|----------|----------------|\n| 1 | **When did the headache and fever start, and how have they progressed?** | Determines duration, pattern (sudden vs. gradual), and whether the fever is rising, persistent, or resolving. A sudden onset or rapidly worsening fever may point toward more serious etiologies. |\n| 2 | **Can you describe the headache (location, quality, intensity, aggravating/relieving factors) and any associated symptoms (neck stiffness, photophobia, nausea/vomiting, visual changes, cough, sore throat, sinus pain, recent exposure to sick contacts, recent travel, medication use)?** | Helps differentiate tension‑type, migraine, sinus, meningitic, or systemic infection. Associated symptoms can reveal the underlying source (e.g., sinus tenderness → sinusitis; photophobia + neck stiffness → meningitis). |\n| 3 | **Do you have any red‑flag risk factors or medical history (immunocompromise, recent head trauma, known chronic illness, recent dental work, use of immunosuppressive meds, recent vaccination, or a history of similar episodes)?** | Identifies patients who may need urgent evaluation or a different work‑up (e.g., immunocompromised patients are at higher risk for serious infections). |\n\n**Additional points the clinician may explore (if time permits):**  \n- Current temperature measurement and trends.  \n- Hydration status, recent sleep patterns, caffeine or alcohol intake.  \n- Any recent changes in medication or new over‑the‑counter remedies.  \n- Impact on daily activities and need for analgesics.\n\n**Next steps (general guidance):**  \n- If the headache is mild, fever ≤ 38 °C (100.4 °F), and no red‑flag features are present, symptomatic care (adequate hydration, antipyretics such as acetaminophen or ibuprofen, rest) and close follow‑up in 48‑72 hours is reasonable.  \n- Advise the patient to return sooner (or go to urgent care/ER) if they develop worsening pain, fever > 38.5 °C, neck stiffness, confusion, new neurological deficits, vomiting, rash, or any other concerning change.  \n\n*This information is educational and not a substitute for an in‑person clinical evaluation.*	CONFIRMED	I have headache and mild fever	2	7
\.


--
-- Data for Name: doctor; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.doctor (id, slot_duration_minutes, specialization, working_hours_end, working_hours_start, user_id) FROM stdin;
1	30	Cardiology	18:00	09:00	2
2	30	Physician	17:00	09:00	11
\.


--
-- Data for Name: doctor_leave_days; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.doctor_leave_days (doctor_id, leave_days) FROM stdin;
\.


--
-- Data for Name: prescription; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.prescription (id, duration_days, frequency_per_day, instructions, medication_name, appointment_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, email, name, password, role) FROM stdin;
1	test@example.com	Test User	$2a$10$PNyn5GVyUgfgRoUWcQbDRuM3evs7gULLQ64dARVCMQZRqoFTCLTNy	PATIENT
2	doctor@example.com	Dr. Test	$2a$10$a6/yLLdn3TTU2nzDqT4wZ.RQ6qq92KOjPEFvvax4sJDzRrR0mssXa	DOCTOR
3	rahul.sharma@example.com	Rahul Sharma	$2a$10$TaP2XqBj/jauPsZEQ9Tm5e0PvLd1i7WViufRIV28C1rJjGsx9lw6K	PATIENT
4	arjun.mehta@example.com	Dr. Arjun Mehta	$2a$10$dEJ/W.Spad1LwOIdKeFuLO43QckwicM9ZTGoBe597LB.5RvN7uEG.	DOCTOR
6	jyotimanocha1756@gmail.com	Jyoti Manocha	$2a$10$Bo.jfyVQO480gc76x02f4e2fHL7.1AC8UTd425J6nS7x5ND0/yUGG	PATIENT
7	jyotimanocha24@gmail.com	Jyoti Manocha	$2a$10$5YLwqtY.9hAEQrPbhDnphux8ge43BJbpwiXzsSoqKBvFYvhIKot7.	PATIENT
5	ujjwalmanocha1756@gmail.com	Ujjwal Manocha	$2a$10$WhCk148Hq6JLAUn32gbIX.1QmV7YhA2WBnIHNlVuHXG6GWsoXnA7S	ADMIN
8	bhavyamanocha849@gmail.com	Bhavya Manocha	$2a$10$xlR/aOaHiWBxLvnxOMsqO.rCUPa3OsoBWmqcrXvtB4YPuHTs4Ez7O	PATIENT
9	neeraj74manocha@gmail.com	Neeraj Manocha	$2a$10$h0iCab4n3z5/HidnL/Ize.jt8nnrNUfxVWCYU7r7LA2crN48SBVze	PATIENT
10	ujjwalmanocha17@gmail.com	Dr Rajesh Jain	$2a$10$Ge3RYXceJDipXUuQ/MoBx.h2MpqVaVMoOOWofdgK1VOWF24i0cHO2	DOCTOR
11	ujjwal1234m@gmail.com	Dr.Ramesh Jain	$2a$10$oWgcqLGatuTuEe/xWqlukOiA0SYjJ7tzaodYVY3Yc46BjSuig4eb.	DOCTOR
\.


--
-- Name: appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.appointment_id_seq', 11, true);


--
-- Name: doctor_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.doctor_seq', 51, true);


--
-- Name: prescription_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.prescription_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 11, true);


--
-- Name: appointment appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT appointment_pkey PRIMARY KEY (id);


--
-- Name: doctor doctor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor
    ADD CONSTRAINT doctor_pkey PRIMARY KEY (id);


--
-- Name: prescription prescription_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prescription
    ADD CONSTRAINT prescription_pkey PRIMARY KEY (id);


--
-- Name: doctor uk3q0j5r6i4e9k3afhypo6uljph; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor
    ADD CONSTRAINT uk3q0j5r6i4e9k3afhypo6uljph UNIQUE (user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: uq_doctor_slot_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_doctor_slot_active ON public.appointment USING btree (doctor_id, appointment_date, appointment_time) WHERE ((status)::text <> 'CANCELLED'::text);


--
-- Name: doctor fk11wrxiolc8qa2e64s32xc2yy4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor
    ADD CONSTRAINT fk11wrxiolc8qa2e64s32xc2yy4 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: prescription fkba3shvghb1nrydjy9khc9c6a7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prescription
    ADD CONSTRAINT fkba3shvghb1nrydjy9khc9c6a7 FOREIGN KEY (appointment_id) REFERENCES public.appointment(id);


--
-- Name: appointment fkkmgspx6jj6lf80ayfwccy2n63; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT fkkmgspx6jj6lf80ayfwccy2n63 FOREIGN KEY (patient_id) REFERENCES public.users(id);


--
-- Name: doctor_leave_days fklpxbarssi0jo8vcyd12wdiyhf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor_leave_days
    ADD CONSTRAINT fklpxbarssi0jo8vcyd12wdiyhf FOREIGN KEY (doctor_id) REFERENCES public.doctor(id);


--
-- Name: appointment fkoeb98n82eph1dx43v3y2bcmsl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT fkoeb98n82eph1dx43v3y2bcmsl FOREIGN KEY (doctor_id) REFERENCES public.doctor(id);


--
-- PostgreSQL database dump complete
--

\unrestrict IRESrfHz4ooK9o20nQoQDuTle3yrj7bXsyKauwhPDJH6iKCv3D2fWkh7akm57mH

